/*
 * Timer.h
 *
 * Created: 1/31/2023 8:08:10 AM
 *  Author: lenovo
 */ 


#ifndef TIMER_H_
#define TIMER_H_
#include "../../Utilities/STD_TYPES.h"

#include "../../Utilities/register.h"
/*
 * Options:
 			1-TIMER0_NORMAL_MODE	2-TIMER0_PWM_MODE
 			3-TIMER0_CTC_MODE		4-TIMER0_FAST_PWM_MODE
 */
#define TIMER0_MODE		TIMER0_NORMAL_MODE
/*
 * Options:
			1- TIMER0_NO_CLK					2- TIMER0_CLK_NO_PRESCALER
			3- TIMER0_CLK_DIVIDED_BY_8			4- TIMER0_CLK_DIVIDED_BY_64
			5- TIMER0_CLK_DIVIDED_BY_256		6- TIMER0_CLK_DIVIDED_BY_1024
			7- TIMER0_CLK_ON_FALLING_EDGE		8- TIMER0_CLK_ON_RISING_EDGE
 */

#define TIMER0_SELECT_CLK	TIMER0_CLK_NO_PRESCALER

/*
 * Options:
 			1-COMPAR_MATCH_INTERRUPT_ENABLE
 			2-OVERFLOW_INTERRUPT_ENABLE
 */
#define TIMER0_INTERRUPT_ENABLE		TIMER0_OVERFLOW_INTERRUPT_ENABLE

#define  TIMER0_COMPAR_MATCH_INTERRUPT_ENABLE	1
#define  TIMER0_OVERFLOW_INTERRUPT_ENABLE		2

/*Options for Clock Select*/
#define TIMER0_NO_CLK					0
#define TIMER0_CLK_NO_PRESCALER			1
#define TIMER0_CLK_DIVIDED_BY_8			2
#define TIMER0_CLK_DIVIDED_BY_64		3
#define TIMER0_CLK_DIVIDED_BY_256		4
#define TIMER0_CLK_DIVIDED_BY_1024		5
#define TIMER0_CLK_ON_FALLING_EDGE		6
#define TIMER0_CLK_ON_RISING_EDGE		7

#define TIMER0_NORMAL_MODE		1
#define TIMER0_CTC_MODE			2
#define TIMER0_PWM_MODE			3
#define TIMER0_FAST_PWM_MODE	4


u8 MTIMER0_voidInitialize(void);
u8 MTIMER0_START(void);
u8 MTIMER0_STOP(void);
u8 MTIMER0_delay(u32 desired_time);





#endif /* TIMER_H_ */